### ISSUE TITLE
Regkey is not available

### ISSUE THREAD

**Issue by BurgerhoutJ** [tabs-not-spaces/Intune.HV.Tools#16]
I'm trying to run this tool on my Hyper-V Server 2019, but when I chooses a image, number 5 in my case, then I get an error stating that the HKLM:\Software\Microsoft\Windows NT\CurrentVersion\WinPE path is unavailable, because it doesn't exist.

![image](https://user-images.githubusercontent.com/25769575/120645515-ced33580-c478-11eb-90c1-79930771a0d1.png)

Any advise?

**Comment by jonod8698** [comment]
Had the same error initially. After reinstalling all PowerShell modules a couple of times I managed to get it to work.

Also, are you using PowerShell 7?

**Comment by BurgerhoutJ** [comment]
I'm using Powershell 7 at the Hyper-V Server 2019.
Reinstalled Powershell 7 again, installed all the powershell modules again, but now I have a different error message.
![image](https://user-images.githubusercontent.com/25769575/120991008-7ace9680-c781-11eb-9932-4392f2222e6b.png)

**Comment by tabs-not-spaces** [comment]
if you can confirm that this issue can be reproduced on 2019 I will look into it

**Comment by BurgerhoutJ** [comment]
Didn't tried it anymore, so for now i'll close this one.
