### ISSUE TITLE
Feature Request: Upload HW hash for Autopilot Enrollment

### ISSUE THREAD

**Issue by BurgerhoutJ** [tabs-not-spaces/Intune.HV.Tools#17]
It would be nice that the HW hash from the VM(s) is uploaded automatically in to your tenant for a complete Autopilot enrollment. Now I have to upload the HW hash manually.

**Comment by tabs-not-spaces** [comment]
We have the functionality to do "offline enrolment" with pulling the JSON down from azure during the provisioning of the VM already. There are design challenges to implement an automated hw upload.

When do you imagine the hardware hash can be harvested? Potentially we could capture it once the device is at OOBE, but even if that were possible via PS Direct / PSRemoting, it's still going to take upwards of 15 minutes to upload and enroll the hardware hash.

With regards to PS Direct / PSRemoting which requires at least one local account on the device to allow authentication, would you imagine allowing configuration of that from within the HV.Tools configuration cmdlets?

The current solution is to either utilize the offline enrollment method which has its own issues, or simply open the console at OOBE on the device and enroll manually.

**Comment by BurgerhoutJ** [comment]
What I forgot to mention is also the ability to set Grouptags. Especially if you want to setup multiple deployment profiles.

**Comment by tabs-not-spaces** [comment]
this wont work as fast as you want it to.
