### ISSUE TITLE
Error add-imagetoconfig

### ISSUE THREAD

**Issue by tjmklaver** [tabs-not-spaces/Intune.HV.Tools#19]
When trying to add image based on ISO I receive the error message:
Building reference image..Convert-WindowsImage: Cannot validate argument on parameter 'Edition'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.

The command does not prompt me to choose the correct edition

I'm using PS 7.1.3 (x64) and tried different ISO's but with same error message
ISO's come from myvisualstudio URL
en_windows_10_business_editions_version_21h1_x64_dvd_ec5a76c1.iso
en_windows_10_business_editions_version_20h2_updated_march_2021_x64_dvd_c2f10533.iso
en_windows_10_business_editions_version_2004_updated_april_2021_x64_dvd_6ffb5872.iso

**Comment by matdew** [comment]
I'm having this same error, using an .iso from the MediaCreationTool

**Comment by matdew** [comment]
In my case, I didn't have an install.wim in the .iso file, just install.esd, but was able to convert that to a WIM, then VHDX and use Add-ImageToConfig with the -ReferenceVHDX parameter.
When New-ClientVHDX calls Get-ImageIndexFromWim, it assumes a .wim will be present.
Get-WindowsImage appears to support .esd files, but Convert-WindowsImage will require a .vhdx

I'm not sure it's within scope to fix this and support ISOs with install.esd, but it would be nice.

**Comment by nalditopr** [comment]
I used NTLite to load the multiple edition ISO and then export a specific version with add-imagetoconfig.

**Comment by tabs-not-spaces** [comment]
this will work if you are using the multi edition iso from msdn / visualstudio. don't know what else to say. more proof there is an issue is required.
