### ISSUE TITLE
Write-error

### ISSUE THREAD

**Issue by chield** [tabs-not-spaces/Intune.HV.Tools#20]
Hi,

when I try to run the add-imagetoconfig cmdlet I receive this error: Building reference image..Write-Error: The media is write protected. (Exception from HRESULT: 0x80070013)

It will let me to choose the image name of the ISO, but then the write error popsup.

**Comment by chield** [comment]
found out that it had to do with the Bitlocker device config that was applied to my machine.

**Comment by chield** [comment]
change the Bitlocker device config and everything is working fine now. Keep up the good work!

**Comment by J-Hoff389** [comment]
@chield Would you mind sharing which bitlocker configuration setting worked for you? I've run into the same issue.
