### ISSUE TITLE
New-ClientDevice - No handling for empty HGS Guardian

### ISSUE THREAD

**Issue by hkystar35** [tabs-not-spaces/Intune.HV.Tools#6]
Private function `New-ClientDevice` uses existing HGS Guardian for creating a key protector, but does not do a check for whether or not one exists, nor does it create one.

Suggestion is to add this after line 42:
```powershell
    If (!$owner)
    {
      # Creating new UntrustedGuardian since it did not exist
      $owner = New-HgsGuardian -Name UntrustedGuardian –GenerateCertificates
    }
```

**Comment by tabs-not-spaces** [comment]
closed by #7
