### ISSUE TITLE
JSON File format for autopilot offline deployment

### ISSUE THREAD

**Issue by KarelPelck** [tabs-not-spaces/Intune.HV.Tools#8]
the JSON file is not accepted for starting the autopilot process. It's created in UTF8 format. It needs to be in ASCII or ANSI format.

https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/existing-devices

**Comment by tabs-not-spaces** [comment]
Aware of that limitation and the code is actually encoding the file to ASCII

https://github.com/tabs-not-spaces/Intune.HV.Tools/blob/308ecff517b42646a827e9e22716c9223a95b65f/Intune.HV.Tools/Private/Get-AutopilotPolicy.ps1#L42-L43

Am curious to how you identified it wasn't being encoded properly or if you can identify where the error exists.

**Comment by tabs-not-spaces** [comment]
closing for now as I can't replicate any issues and the file is 100% being encoded correctly.
